## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
unique = application_df.nunique()
unique

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
type_count = application_df['APPLICATION_TYPE'].value_counts()
type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_count = application_df['CLASSIFICATION'].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_count_1 = class_count[class_count > 1]
class_count_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(class_count[class_count<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_dummies_df = pd.get_dummies(application_df)
application_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_dummies_df['IS_SUCCESSFUL']
X = application_dummies_df.drop(columns='IS_SUCCESSFUL', axis=1)

In [14]:
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [15]:
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [16]:
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [19]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=X_train_scaled.shape[1]))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=15, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))
# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4160

 dense_1 (Dense)             (None, 15)                1215

 dense_2 (Dense)             (None, 1)                 16

=================================================================
Total params: 5391 (21.06 KB)
Trainable params: 5391 (21.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [22]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 3s 2ms/step - loss: 1.1602 - accuracy: 0.6967
Epoch 2/150
804/804 [==============================] - 2s 3ms/step - loss: 0.9740 - accuracy: 0.7193
Epoch 3/150
804/804 [==============================] - 2s 2ms/step - loss: 1.0516 - accuracy: 0.7105
Epoch 4/150
804/804 [==============================] - 2s 2ms/step - loss: 1.0006 - accuracy: 0.7107
Epoch 5/150
804/804 [==============================] - 2s 2ms/step - loss: 0.8319 - accuracy: 0.7153
Epoch 6/150
804/804 [==============================] - 2s 2ms/step - loss: 0.6894 - accuracy: 0.7273
Epoch 7/150
804/804 [==============================] - 2s 2ms/step - loss: 0.6775 - accuracy: 0.7261
Epoch 8/150
804/804 [==============================] - 2s 2ms/step - loss: 0.6640 - accuracy: 0.7260
Epoch 9/150
804/804 [==============================] - 2s 2ms/step - loss: 0.6491 - accuracy: 0.7284
Epoch 10/150
804/804 [==============================] - 2s 3ms/step - loss: 0.6210 - accuracy: 0.7311
Epoch 11/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5969 - accuracy: 0.7312
Epoch 12/150
804/804 [==============================] - 2s 2ms/step - loss: 0.6112 - accuracy: 0.7298
Epoch 13/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5971 - accuracy: 0.7280
Epoch 14/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5860 - accuracy: 0.7320
Epoch 15/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5888 - accuracy: 0.7343
Epoch 16/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5902 - accuracy: 0.7343
Epoch 17/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5872 - accuracy: 0.7343
Epoch 18/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5903 - accuracy: 0.7320
Epoch 19/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5895 - accuracy: 0.7325
Epoch 20/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5906 - accuracy: 0.7297
Epoch 21/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5896 - accuracy: 0.7326
Epoch 22/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5816 - accuracy: 0.7347
Epoch 23/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5813 - accuracy: 0.7352
Epoch 24/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5846 - accuracy: 0.7342
Epoch 25/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5850 - accuracy: 0.7325
Epoch 26/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5674 - accuracy: 0.7328
Epoch 27/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5655 - accuracy: 0.7341
Epoch 28/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5655 - accuracy: 0.7348
Epoch 29/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5666 - accuracy: 0.7343
Epoch 30/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5628 - accuracy: 0.7353
Epoch 31/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5670 - accuracy: 0.7345
Epoch 32/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5684 - accuracy: 0.7327
Epoch 33/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5643 - accuracy: 0.7344
Epoch 34/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5607 - accuracy: 0.7336
Epoch 35/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5820 - accuracy: 0.7297
Epoch 36/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5709 - accuracy: 0.7356
Epoch 37/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5646 - accuracy: 0.7346
Epoch 38/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7360
Epoch 39/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5623 - accuracy: 0.7352
Epoch 40/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5822 - accuracy: 0.7367
Epoch 41/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5717 - accuracy: 0.7357
Epoch 42/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5651 - accuracy: 0.7350
Epoch 43/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5598 - accuracy: 0.7345
Epoch 44/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5670 - accuracy: 0.7364
Epoch 45/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5695 - accuracy: 0.7356
Epoch 46/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5719 - accuracy: 0.7369
Epoch 47/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5697 - accuracy: 0.7355
Epoch 48/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5640 - accuracy: 0.7361
Epoch 49/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5598 - accuracy: 0.7367
Epoch 50/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5709 - accuracy: 0.7376
Epoch 51/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5647 - accuracy: 0.7341
Epoch 52/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5632 - accuracy: 0.7350
Epoch 53/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5676 - accuracy: 0.7352
Epoch 54/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5610 - accuracy: 0.7372
Epoch 55/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5586 - accuracy: 0.7374
Epoch 56/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5610 - accuracy: 0.7368
Epoch 57/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5652 - accuracy: 0.7375
Epoch 58/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5617 - accuracy: 0.7380
Epoch 59/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5620 - accuracy: 0.7369
Epoch 60/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5655 - accuracy: 0.7334
Epoch 61/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5624 - accuracy: 0.7378
Epoch 62/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5634 - accuracy: 0.7378
Epoch 63/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5642 - accuracy: 0.7372
Epoch 64/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5814 - accuracy: 0.7299
Epoch 65/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5672 - accuracy: 0.7357
Epoch 66/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5607 - accuracy: 0.7361
Epoch 67/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5631 - accuracy: 0.7357
Epoch 68/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5597 - accuracy: 0.7374
Epoch 69/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5559 - accuracy: 0.7378
Epoch 70/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5545 - accuracy: 0.7389
Epoch 71/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7375
Epoch 72/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5580 - accuracy: 0.7385
Epoch 73/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7378
Epoch 74/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7375
Epoch 75/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5612 - accuracy: 0.7380
Epoch 76/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5582 - accuracy: 0.7370
Epoch 77/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5562 - accuracy: 0.7379
Epoch 78/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7386
Epoch 79/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5591 - accuracy: 0.7380
Epoch 80/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5610 - accuracy: 0.7373
Epoch 81/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5582 - accuracy: 0.7368
Epoch 82/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7388
Epoch 83/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7391
Epoch 84/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5572 - accuracy: 0.7382
Epoch 85/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5613 - accuracy: 0.7387
Epoch 86/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5645 - accuracy: 0.7391
Epoch 87/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5686 - accuracy: 0.7383
Epoch 88/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5671 - accuracy: 0.7392
Epoch 89/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5651 - accuracy: 0.7392
Epoch 90/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5642 - accuracy: 0.7386
Epoch 91/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5672 - accuracy: 0.7394
Epoch 92/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5651 - accuracy: 0.7383
Epoch 93/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5666 - accuracy: 0.7388
Epoch 94/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5660 - accuracy: 0.7391
Epoch 95/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5643 - accuracy: 0.7401
Epoch 96/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5647 - accuracy: 0.7387
Epoch 97/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5689 - accuracy: 0.7397
Epoch 98/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5649 - accuracy: 0.7387
Epoch 99/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5684 - accuracy: 0.7389
Epoch 100/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5662 - accuracy: 0.7383
Epoch 101/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5644 - accuracy: 0.7394
Epoch 102/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5648 - accuracy: 0.7400
Epoch 103/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5666 - accuracy: 0.7389
Epoch 104/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5663 - accuracy: 0.7404
Epoch 105/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5629 - accuracy: 0.7401
Epoch 106/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5664 - accuracy: 0.7370
Epoch 107/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5644 - accuracy: 0.7398
Epoch 108/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5622 - accuracy: 0.7402
Epoch 109/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5698 - accuracy: 0.7393
Epoch 110/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7402
Epoch 111/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5642 - accuracy: 0.7393
Epoch 112/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5624 - accuracy: 0.7400
Epoch 113/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7396
Epoch 114/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5628 - accuracy: 0.7403
Epoch 115/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5652 - accuracy: 0.7406
Epoch 116/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5647 - accuracy: 0.7402
Epoch 117/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5645 - accuracy: 0.7400
Epoch 118/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5684 - accuracy: 0.7398
Epoch 119/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5635 - accuracy: 0.7398
Epoch 120/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5662 - accuracy: 0.7393
Epoch 121/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5669 - accuracy: 0.7402
Epoch 122/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5647 - accuracy: 0.7394
Epoch 123/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5643 - accuracy: 0.7393
Epoch 124/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5584 - accuracy: 0.7383
Epoch 125/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5557 - accuracy: 0.7395
Epoch 126/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7416
Epoch 127/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7401
Epoch 128/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5606 - accuracy: 0.7399
Epoch 129/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7381
Epoch 130/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7401
Epoch 131/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5558 - accuracy: 0.7409
Epoch 132/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5550 - accuracy: 0.7398
Epoch 133/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7395
Epoch 134/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5592 - accuracy: 0.7405
Epoch 135/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5606 - accuracy: 0.7413
Epoch 136/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5647 - accuracy: 0.7383
Epoch 137/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7397
Epoch 138/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7395
Epoch 139/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5573 - accuracy: 0.7395
Epoch 140/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5594 - accuracy: 0.7395
Epoch 141/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7400
Epoch 142/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5577 - accuracy: 0.7407
Epoch 143/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5627 - accuracy: 0.7394
Epoch 144/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5781 - accuracy: 0.7286
Epoch 145/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5701 - accuracy: 0.7389
Epoch 146/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5650 - accuracy: 0.7397
Epoch 147/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5618 - accuracy: 0.7395
Epoch 148/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5570 - accuracy: 0.7401
Epoch 149/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5597 - accuracy: 0.7412
Epoch 150/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7408

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6297 - accuracy: 0.7222 - 482ms/epoch - 2ms/step
Loss: 0.6297463178634644, Accuracy: 0.7222157716751099

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE